[package]
name = "halo2-fri-verifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = { version = "0.11.0", default-features = false }
plonky2 = { git = "https://github.com/0xpolygonzero/plonky2" }
starky = { git = "https://github.com/0xpolygonzero/plonky2" }
goldilocks = { path = "../goldilocks" }

[dev-dependencies]
anyhow = { version = "1.0.40", default-features = false }
env_logger = { version = "0.9.0", default-features = false }
rand = "0.8.5"
serde_json = "1.0"
tiny-keccak = "2.0.2"

[patch."https://github.com/0xpolygonzero/plonky2"]
plonky2 = { path = "../plonky2/plonky2" }
starky = { path = "../plonky2/starky" }
